### ISSUE TITLE
pojson crash with Python 3.2

### ISSUE THREAD

**Issue by DerDakon** [obviel/pojson#7]
The details can be seen here: https://travis-ci.org/OpenRailwayMap/OpenRailwayMap/jobs/349065856

pojson ca_ES/LC_MESSAGES/messages.po > ca_ES/LC_MESSAGES/messages.json
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.2.6/bin/pojson", line 7, in <module>
    from pojson.main import main
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/pojson/__init__.py", line 2, in <module>
    from pojson.convert import po2dict, convert
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/pojson/convert.py", line 18
    key = u'{0}\x04{1}'.format(entry.msgctxt, entry.msgid)
                      ^
SyntaxError: invalid syntax

The code in question is https://github.com/OpenRailwayMap/OpenRailwayMap/pull/604

**Comment by rurseekatze** [comment]
https://docs.python.org/3/library/stdtypes.html#text-sequence-type-str says:

> Changed in version 3.3: For backwards compatibility with the Python 2 series, the u prefix is once again permitted on string literals. It has no effect on the meaning of string literals and cannot be combined with the r prefix.
